### ISSUE TITLE
Pretrained model on SynthText+IC13+IC17

### ISSUE THREAD

**Issue by Amy-Liao** [gmuffiness/CRAFT-train#1]
Thanks for your work. It is really helpful!

I saw that the original paper had a model trained on SynthText + IC13 + IC17. I'm wondering that if you also have trained weights training on these dataset too? I'm trying to train on my custom data based on the pretrained model but the original paper didn't provide the optimizer's and scaler's state_dict.
Thank you.

**Comment by gmuffiness** [comment]
I'm glad it helped!

Unfortunately, I haven't tried the settings you mentioned.
But I think with a little hyperparameter tuning, the settings you mentioned will also have similar performance to the original paper.

Thanks.
